
services:
  db:
    image: postgres:15-alpine
    container_name: jobseeker-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jobseeker_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: jobseeker-api
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://user:password@db:5432/jobseeker_db
    depends_on:
      - db

volumes:
  pgdata: